EDCD/coriolis

- package.json
- src/app/Coriolis.jsx
> fix zbuf error

- src/app/components/AvailableModulesMenu.jsx
Fixes https://github.com/EDCD/coriolis/issues/155
> Fix repair limpet grouping

- src/app/components/InternalSlot.jsx
Prevents errors like #156 happening again
> prevent crashing when no modifications are in the data

- src/app/components/EngagementRange.jsx
- src/app/utils/CompanionApiUtils.js
Fixes #158 
coriolis-data PR: https://github.com/EDCD/coriolis-data/pull/14
You're welcome 😉
> [WIP] [no merge yet] Feature/fix engineers

- src/app/utils/CompanionApiUtils.js
See https://github.com/EDCD/coriolis/issues/188#issuecomment-357238270
> Fix clip size (hopefully)

- package-lock.json
- package.json
- src/app/Coriolis.jsx
- src/app/pages/OutfittingPage.jsx
- src/app/shipyard/ModuleUtils.js
- src/app/shipyard/Ship.js
- src/app/utils/CompanionApiUtils.js
- src/app/utils/JournalUtils.js
- webpack.config.dev.js
Decided to split journal imports to a separate file.
Checklist:
> [WIP] [3.0] Beyond Coriolis [Don't merge yet]

- src/app/components/StandardSlot.jsx
- src/app/pages/ShipyardPage.jsx
Trying this again after working with @joelgarboden
Fixes #209
> Added fuel tank column to Core Module Classes on Shipyard

- src/app/shipyard/Ship.js
Check that the passenger property is defined for a slot before calculating total passenger capacity
> Fix for issue 245

- src/app/utils/BlueprintFunctions.js
Old function was actually hitting values below the possible minimum and the random function handled it correctly.
> reused random functionality as it worked better on percentage rolls between min max

- src/app/components/ModificationsMenu.jsx
I think this makes more sense with the new system
> (optional) changed roll presets to 0-50-100

- src/app/components/ModificationsMenu.jsx
- src/less/buttons.less
Applied some of the design guide on the menu. The flow for assigning blue prints is as follows:
no bp -> directly on bp selection screen -> special selection -> value screen
has bp -> directly on value screen
hope you like it :)
> blue print workflow (easier editing of modules)

- src/app/Coriolis.jsx
- src/app/components/AvailableModulesMenu.jsx
- src/app/components/Header.jsx
- src/app/components/ModificationsMenu.jsx
- src/app/components/ShipSummaryTable.jsx
- src/app/components/Slider.jsx
- src/app/components/Slot.jsx
- src/app/components/StandardSlot.jsx
- src/app/pages/OutfittingPage.jsx
- src/app/pages/ShipyardPage.jsx
- src/app/shipyard/Module.js
- src/app/shipyard/ShipRoles.js
- src/app/utils/BlueprintFunctions.js
- src/app/utils/CompanionApiUtils.js
- src/app/utils/JournalUtils.js
Reduces the lint errors from 503 to 41. The remaining ones are mostly:
* JSDoc additions
* Not mutating `state` directly
* No console commands
I'll let the maintainers worry about those.
Quite frankly, these were fixed very easily and should have been caught before they were ever merged into the code base. PR #300 should at least allow Travis to truly show whether lint and tests are passing or not.
> Fix obvious lint issues

- src/app/components/Defence.jsx
- src/app/shipyard/Calculations.js
- src/app/shipyard/Module.js
- src/app/shipyard/Ship.js
In this PR I introduced caps to resistances for shields and armour.
I especially changed how shield and armour metrics are being calculated. It would be good if someone would have a look at the `armour.explosive`, `.kinetic`, ..., `shield.explosive`, ... values and check whether my changes keep the project as a whole intact.
Closes #324 #305 
References #275
> Caps for resistances introduced

- src/app/components/HardpointSlot.jsx
- src/app/shipyard/Calculations.js
- src/app/shipyard/Module.js
PR title is self explanatory. It is check-worthy how exactly auto-loader effects SDPS. I implemented it such that if auto-loader is applied, we take the clipsize as being `clipsize + clipsize - 1`.
Closes #326
> SDPS takes autoloader into account

- src/app/utils/JournalUtils.js
> Shieldboosters imported correctly now

- src/app/shipyard/Calculations.js
- src/app/shipyard/Module.js
- src/app/shipyard/Ship.js
> Various fixes

- package.json
- src/app/components/Pips.jsx
- src/app/i18n/en.json
- src/app/pages/OutfittingPage.jsx
- src/less/pips.less
I also restructured much of the `Pips.jsx` because there was a *lot* of redundancy. I stripped that away as far as I could. Overall it got a bit shorter!
> Add multicrew pips

- src/app/utils/JournalUtils.js
> Fix journal import

- src/app/components/VerticalBarChart.jsx
> Fix VerticalBarchart labels

- src/app/shipyard/Module.js
- src/app/shipyard/Ship.js
> Apply diminishing returns for hull resistance modding to all modules

- src/app/pages/ShipyardPage.jsx
- src/less/table.less
see issue https://github.com/EDCD/coriolis/issues/446
> Fix background highlight on sort in shipyard

- src/app/components/Defence.jsx
- src/app/shipyard/Module.js
- src/app/shipyard/Ship.js
> Multiple bug fixes

- src/app/components/Header.jsx
> Fix ships menu not sorted by name

- src/app/components/ShipSummaryTable.jsx
- src/app/i18n/cn.json
- src/app/i18n/fr.json
- src/app/i18n/ru.json
- src/app/shipyard/Calculations.js
- src/app/shipyard/Constants.js
- src/app/shipyard/Module.js
Fixes bugs that have been induced by the latest changes to rof calculations as well as old ones.
> Fixes to DPS and ROF calculations

- src/app/components/AvailableModulesMenu.jsx
- src/app/components/Slot.jsx
Main change: added constraint to not equip more than 4 experimental weapons
Needs https://github.com/EDCD/coriolis-data/pull/73 to work but can be merged without that
> Not more than 4 experimentals

- src/app/components/ModalImport.jsx
This is something that has been bothering me for a while. I move my ships between computers regularly and the fact that the module discount never stuck was frustrating, so I decided to fix it.
> Fix backup import to properly handle module discount.

- src/app/i18n/en.json
> Minor typo fix

- src/app/shipyard/Module.js
This should fix #473 - shield values confirmed with a few different Enhanced Low Power shields.
> Shield engineering should not modify max mass

- src/app/shipyard/Calculations.js
I happened to be looking at the file and saw this code is unreferenced/dead.
> Remove dead code

- src/app/shipyard/Module.js
Fixed calculations for modification values according to #624. Previous version of calculations was weird for me, but point me if I'm missing something.
@felixlinker please check
> Corrected calculations of modification values

- src/app/utils/JournalUtils.js
This is an adapted version of the solution provided in the https://github.com/EDCD/coriolis/pull/647  (Issue #631)
Cause that PR got a little stuck :)
This changes only the logic, where if the Modifications are missing it takes the Quality to calculate the engineered module's properties.
As I tried with different exports from Inara and EDSM and there seems to be a little difference but it's usually around 1%.
> Fix for engineered modules in SLEF imports from Inara.

- src/app/components/AvailableModulesMenu.jsx
- src/app/i18n/en.json
*Addressed the comments and turned it into a PR for easier management*
This patchset moves the Multi limpet controllers to below repair limpet controllers, and sorts them by name for easier reading
> Minor modifications for Multi-limpet Controllers

- src/app/shipyard/Calculations.js
> Revert "shield recovery time depending on distributor draw"

- src/app/components/ModalShoppingList.jsx
Fixes #705, #582, #692, #677, #466, #656, and #607 
To be merged with sister PR [here](https://github.com/EDCD/coriolis-data/pull/91)
Untested, because my machine can't run EDEngineer
> Add mats for experimental effects to mat list

- src/app/shipyard/Constants.js
> Quick fix for missing group info in JSON exports

- src/app/shipyard/Constants.js
* Adding missing Constants for Advanced and Enhanced Weaponry
> Fix missile rack glitch (#23)
