- src/app/utils/SlotFunctions.js
Adds commas to the cost of modules when hovering over them. Not only is this more clear, but it is consistent with the way all other costs are rendered.
Closes #169
> Add commas to slot cost

- src/app/pages/ShipyardPage.jsx
Adds passenger totals to the shipyard page. Should handle if a certain slot is limited to one type of passenger bay, ie. luxury passenger bay only.
Fixes Issue #186
> Issue #186. Added passenger totals to shipyard screen

- devServer.js
Disable host header so webpack allows more than 'localhost' access
Allow easier remote IE/Safari/Chrome/Edge compatibility testing.
I believe this also prepares for [webpack 2.4.3](https://github.com/webpack/webpack-dev-server/issues/882) changes.
> Disable 'localhost' host header requirement

- .travis.yml
Travis builds have been failing since [Nov 7, 2017](https://github.com/EDCD/coriolis/commit/94d06e40254d6b171ceeb0063421899adf9a9fed), where linting and tests both started failing. The [subsequent commit](https://github.com/EDCD/coriolis/commit/0d6aa87e89f9529db7e8f35ff7b4743cedb94bd6), which changed `package.json` to use `../coriolis-data` instead of `EDCD/coriolis-data`, has left Travis builds in error state ever since. That's because npm doesn't see `coriolis-data` in the parent directory (unsurprisingly).
This PR will fix the npm install issue. You'll see [in the corresponding Travis build](https://travis-ci.org/BenJuan26/coriolis/builds/389263167) that the npm install error has been masking **503 linting errors** and 6 failed tests. Those will have to be fixed outside of this PR.
> Clone coriolis-data into Travis before npm install

- src/app/shipyard/Ship.js
Before this change, removing a blueprints special effect would not update all numbers properly. E. g. look at [this build](https://coriolis.edcd.io/outfit/cobra_mk_iii?code=A2pataFalddasdf4----04-45-----.Iw1%2FkA%3D%3D.Aw1%2FkA%3D%3D.H4sIAAAAAAAAA%2BP558rAwPCXFUj8mQMk%2BO8AmUIGpQwMEkc4GRjkBSIZGP7%2FZwAA3QJ2licAAAA%3D.EweloBhBGA2EoFMCGBzANokMK6A%3D).
If you remove the super capacitors special effect from the build above, nothing will change. My PR fixes that as it maps `clearModuleSpecial` to `setModuleSpecial(m, null)`.
> Resetting special effects for blueprints now re-calculates all stats

- src/app/shipyard/Module.js
- src/app/utils/BlueprintFunctions.js
There are two changes in this PR. Firstly, we don't change the blueprint values for shield boost effects and rather apply the mod to `1+shield booster boost` which leads to numbers that are better aligned with what is displayed ingame and especially inara.
Secondly, special effects for shield boost mods are applied correctly.
Closes #323
> Fixes for shieldboost mods and special effects on shield booster

- src/app/shipyard/Module.js
Shot speed now does not consider special blueprints differently. In my eyes, this was totally unnecessary. However, this PR requires https://github.com/EDCD/coriolis-data/pull/40 to work properly.
> No special treatment for shotspeed modifications anymore

- src/app/components/ShipSummaryTable.jsx
Before, when 0 pips to sys were given, 2 woud be taken as default value. In my eyes, this lead to inconsistent results.
Closes #334
> Ship summary correctly calculates shield recovery/recharge time

- src/app/components/Offence.jsx
- src/app/shipyard/Calculations.js
Two changes:
1. The offence table now lists "native" SDPS values and has an aggregation row at the bottom (see screenshot below)
2. https://github.com/EDCD/coriolis/commit/3febe465f68af433643aa40a9c5e7984ad97e4a6 fixes a bug that was introduced in a8c44fddcae97c7cef1d99b52d4a2009b2c0b029 and d2380a5c9c091ad5deca0a70c959fc10171bbf5b. There, I set the `reinforcement`/`booster` value to be calculated by difference. However, it is expected to be calculated as multiplier in https://github.com/EDCD/coriolis/blob/master/src/app/shipyard/Calculations.js#L876 ff. Other references are not influenced by this change. This leads to effectiveness values being shown correctly. Before they were in the range `[-100%, 0%]`.
Closes #283
> Offence table improved (+Bug fix)

- src/app/components/Defence.jsx
- src/app/shipyard/Calculations.js
Before this PR, in the defence panel when looking at the values that make up total effective shield strength, the resistance value would already contain sys-contributed MJ. See screenshot below.
Now everything works correct.
> Shield defence proportions calculated correctly

- package.json
- src/app/components/LineChart.jsx
- src/app/components/PieChart.jsx
- src/app/components/VerticalBarChart.jsx
- src/app/components/WeaponDamageChart.jsx
I fixed issue #208 by changing a dependency. @willyb321 your guess seems to be right that this issue was caused by `react-measure`. I therefore removed this dependency and added `react-container-dimensions`. This behaves nearly identical however it's approach is a bit more cleaner in my opinion as it doesn't rely on calbacks, etc.
In consequence I needed to use a `<div>` in the `WeaponDamageChart` as that dependency does not seem to work with `<span>`. I couldn't spot a change in the UI therefore I think this is fine.
You might need to update the `package-lock.json`.
Closes #208
> Fixed resize observer loop limit exceeded

- src/app/components/Modification.jsx
References #401
Key change can be found in line 44 where I only set values to the module when we (kind of) can recreate the string entered. This should prevent `1.` to be set to `1`. In that case the script wouldn't set the value as number because it would recognize `1` not being a pre- or suffix of `1.`.
Also pressing Enter commits changes now.
> Enhance number editing

- src/app/utils/SlotFunctions.js
Minor tweak: wrong units show up (as MJ instead of MW) for the pop-ups when you compare other modules than the current one.
OT remark: OMG this is an amazing piece of work folks!
> Fix wrong units for pgen and power in pop-ups

- src/app/pages/Page.jsx
- src/app/pages/ShipyardPage.jsx
- src/less/colors.less
- src/less/table.less
- Click ship rows to highlight them, for easy comparing.
- Removes a custom override for shouldComponentUpdate. My theory is that react is better suited to evaluate this natively, unless there are known performance issues. Since we don't know, give performance a test in beta. 
resolves [Issue#448](https://github.com/EDCD/coriolis/issues/448)
> 448: compare highlights in shipyard

- __tests__/fixtures/expected-builds.json
- __tests__/fixtures/slef-multiple-builds.json
- __tests__/fixtures/slef-multiple-expected-builds.json
- __tests__/fixtures/slef-single-build.json
- __tests__/test-import.js
- src/app/components/ModalImport.jsx
Inara uses the [SLEF] format to export builds. This format is mostly
just a wrapper around the standard journal loadout format and includes
support for source app metadata and exporting of multiple loadouts at
one time. This change adds support for this format in the manual
importer. Eventually it would be good to support this in the import
route as well so Inara (or any other apps) can link directly to
coriolis.
[SLEF]: https://inara.cz/inara-impexp-slef/
Closes #142 
In creating the tests for this feature I found a variety of issues with the current test suite. There seems to have been a small variation in how the data gets compressed and passed into url redirects and the persisted storage. Another issue was with the tests for importing of backups. There was a change a couple years ago …
> Support SLEF import format for importing builds.

- src/app/shipyard/Calculations.js
This adds, alongside https://github.com/EDCD/coriolis-data/pull/79, calculation of jump range with the ship's reserve tank mass taken into account.
> Calculate jump range with a full reserve fuel tank

- README.md
I prefer running coriolis using an existing apache setup, not via node, so document that you can do that.
> README: Call out `npm run build` alternative in developer instructions

- src/app/shipyard/Calculations.js
The offense tab was using sustained DPS and non-sustained EPS to calculate DPE, resulting in incorrect values. This PR corrects this, and the DPE values now equal the values in the module configuration (after taking effectiveness into account).
> Fix DPE calculations on offense tab

- src/app/shipyard/Calculations.js
When engineering shields the distributor draw can vary from 0.6 which was hard-coded in the calculation function. I corrected this and verified new values. Simple check: Change distributor draw manually without change - nothing happens, with change it is calculated correctly.
> shield recovery time depending on distributor draw

- src/app/utils/CompanionApiUtils.js
This fixes the import failure with the Python Mk II.
> Adding python_nx to SHIP_FD_NAME_TO_CORIOLIS_NAME

- src/app/shipyard/ModuleSet.js
Goes hand-in-hand with https://github.com/EDCD/coriolis-data/pull/98. 
Adds a check to not display invalid SCO modules (as they cannot be downsized)
> Add SCO Module Check

- README.md
`http://www.edshipyard.com/` is now owned by a Vietnamese betting company (Mu88). Remove the link to avoid giving them traffic.
I considered replacing the link with an archived version, but, at least for me,  https://web.archive.org/web/20231030223647/http://www.edshipyard.com/ just shows a mostly-white page with some light grey text at the top, so it didn't seem useful.
> Remove link to squatted domain
